apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-broker
  selector:
    app: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - kafka
                topologyKey: kubernetes.io/hostname
      containers:
      - name: bitnami-kafka
        image: "bitnami/kafka:2.1.0"
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
        ports:
        - containerPort: 9092
          name: kafka-broker
        env:
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zk-cs:2181
          # - name: KAFKA_LOGS_DIRS
          #   value: /tmp/k
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 5
        # volumeMounts:
        # - name: datadir
        #   mountPath: /tmp/k
      securityContext:
        runAsUser: 1001
        fsGroup: 1000
  # volumeClaimTemplates:
  # - metadata:
  #     name: datadir
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: manual
  #     resources:
  #       requests:
  #         storage: 20Gi
