apiVersion: v1
kind: Service
metadata:
  name: zk
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    name: zk-cl-port
---
apiVersion: v1
kind: Pod
metadata:
  name: zk-pod
  labels:
    app: zookeeper
spec:
  containers:
  - name: zk-container
    image: "zookeeper:3.4.13"
    ports:
      - containerPort: 2181
        name: zk-cl-port
    env:
      - name: ALLOW_ANONYMOUS_LOGIN
        value: "yes"
    readinessProbe:
      tcpSocket:
        port: 2181
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 2181
      initialDelaySeconds: 15
      periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - port: 9092
#    nodePort: 30001
    name: broker-port
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    app: kafka
spec:
  containers:
  - name: kafka-container
    image: "bitnami/kafka:2.1.0"
    ports:
      - containerPort: 9092
        name: broker-port
    env:
      - name: ALLOW_PLAINTEXT_LISTENER
        value: "yes"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: zk:2181
      - name: KAFKA_ADVERTISED_HOST_NAME
        value: localhost
      - name: KAFKA_BROKER_ID
        valueFrom:
          fieldRef:
            fieldPath: spec.hostname 
    readinessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 15
      periodSeconds: 20
